# Mục mới

In [ ]:
pip install torch torchvision torchaudio


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 67.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 67.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 43.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 68.1 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink

In [ ]:
import torch

In [ ]:
torch.cuda.memory_cached()

<ipython-input-2-aeba71b2fcad>:1: FutureWarning: `torch.cuda.memory_cached` has been renamed to `torch.cuda.memory_reserved`
  torch.cuda.memory_cached()


0

Dataset with pytorch

In [ ]:
# loading data iris
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#
df = pd.read_csv('/content/Iris.csv')
df.head()
df.shape

(150, 6)

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop([ "Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)

# Chia du lieu voi test size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1,1)
#
print(f"train size {len(y_train)}")

train size 120


In [ ]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)
#

tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
# Tinh dao ham bang pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5x + 1
#Tinh y'
# tao mot tensor voi requirements_grad duoc dat thanh True
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)
# Dinh nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)





tensor(2., requires_grad=True)
None
tensor(63., grad_fn=<AddBackward0>)


In [ ]:
y.grad_fn

In [ ]:
# Thực hiện truyền ngược và tính toán các gradient
y.backward()

In [ ]:
x.grad

tensor(93.)

In [ ]:
# BT
# Cho y = 5x^6 + 3x^3 + 2x^1 + x + 2x + 5x^4 + 1
# Tìm độ dốc của đa thức trên tại điểm nào

# x = torch.tensor([1.0], requires_grad=True)
# y = 5*x**6 + 3*x**3 + 2*x**1 + x + 2*x + 5*x**4 + 1
# y.backward()
# x.grad

import torch

# Khai báo giá trị x dưới dạng tensor có tính toán đạo hàm
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y
y = 5*x**6 + 5*x**4 + 3*x**3 + 2*x + x + 2*x + 1

# Tính đạo hàm bằng autograd
y.backward()

# Lấy giá trị đạo hàm tại x
slope = x.grad
print(f"Độ dốc tại x = {x.item()} là: {slope.item()}")



Độ dốc tại x = 2.0 là: 1161.0


In [1]:
# BTVN1
# Tạo 1 tensort x có giá trị ban đầu là 2.0
# Định nghĩa hàm số và tính gradient
# y = x^3 + 2x^2 + 5x + 1
# hãy tính dy/dx tại giá trị của x
# Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

import torch

# Tạo tensor x có giá trị ban đầu là 2.0
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y = x^3 + 2x^2 + 5x + 1
def function(x):
    return x**3 + 2*x**2 + 5*x + 1

# Định nghĩa learning rate
alpha = 0.1

# Thực hiện Gradient Descent trong 10 vòng lặp
for i in range(10):
    # Tính giá trị của hàm số
    y = function(x)

    # Tính gradient của y theo x
    y.backward()

    # Lấy giá trị gradient
    grad = x.grad

    # Cập nhật giá trị của x
    x.data = x.data - alpha * grad

    # Reset gradient về 0 để tránh tích lũy gradient
    x.grad.zero_()

    # In giá trị của x và y sau mỗi vòng lặp
    print(f"Iteration {i+1}: x = {x.item()}, y = {y.item()}")
#


Iteration 1: x = -0.5, y = 27.0
Iteration 2: x = -0.875, y = -1.125
Iteration 3: x = -1.2546875476837158, y = -2.513671875
Iteration 4: x = -1.7250847816467285, y = -4.1001362800598145
Iteration 5: x = -2.427826166152954, y = -6.807298183441162
Iteration 6: x = -3.7249975204467773, y = -13.660883903503418
Iteration 7: x = -6.897680282592773, y = -41.56037521362305
Iteration 8: x = -18.912006378173828, y = -266.51019287109375
Iteration 9: x = -119.14640808105469, y = -6142.375
Iteration 10: x = -4330.74755859375, y = -1663589.5


In [2]:
# BTVN 2
# Tạo 1 tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức
# y = 3x + 5 _ noise
# Với noise là 1 giá trị ngẫu nhiên nhỏ
# Câu 1 khởi tạo tham số w và b ngẫu nhiên với requiré_grad = True
# Câu 2 Tính MSE
# Câu 3 Tính Gradient
# Câu 4 Cập nhật tham số w và b bằng Gradient Descent với Learning rate alpha = 0.01
# Câu 5 Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình
import torch
import numpy as np

# Tạo tập dữ liệu giả lập
np.random.seed(42)  # Để kết quả có thể tái lập
x = np.random.randint(1, 11, size=20)  # Số giờ học (ngẫu nhiên từ 1 đến 10)
noise = np.random.normal(0, 1, size=20)  # Nhiễu ngẫu nhiên
y = 3 * x + 5 + noise  # Số điểm theo công thức y = 3x + 5 + noise

# Chuyển đổi dữ liệu sang tensor
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

# Câu 1: Khởi tạo tham số w và b ngẫu nhiên với requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Định nghĩa hàm dự đoán
def predict(x):
    return w * x + b

# Định nghĩa hàm tính MSE (Mean Squared Error)
def mse_loss(y_true, y_pred):
    return torch.mean((y_true - y_pred) ** 2)

# Định nghĩa learning rate
alpha = 0.01

# Câu 5: Lặp lại quá trình trong 100 vòng lặp
for epoch in range(100):
    # Câu 2: Tính MSE
    y_pred = predict(x)
    loss = mse_loss(y, y_pred)

    # Câu 3: Tính Gradient
    loss.backward()

    # Câu 4: Cập nhật tham số w và b bằng Gradient Descent
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad

    # Reset gradient về 0
    w.grad.zero_()
    b.grad.zero_()

    # In kết quả sau mỗi 10 vòng lặp
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch + 1}: w = {w.item():.4f}, b = {b.item():.4f}, Loss = {loss.item():.4f}")

# Kết quả cuối cùng
print("\nKết quả cuối cùng:")
print(f"w = {w.item():.4f}, b = {b.item():.4f}")

Epoch 10: w = 3.4660, b = 1.4633, Loss = 1.4866
Epoch 20: w = 3.4563, b = 1.5280, Loss = 1.4435
Epoch 30: w = 3.4467, b = 1.5912, Loss = 1.4026
Epoch 40: w = 3.4375, b = 1.6528, Loss = 1.3637
Epoch 50: w = 3.4284, b = 1.7128, Loss = 1.3266
Epoch 60: w = 3.4196, b = 1.7714, Loss = 1.2914
Epoch 70: w = 3.4110, b = 1.8285, Loss = 1.2579
Epoch 80: w = 3.4026, b = 1.8842, Loss = 1.2261
Epoch 90: w = 3.3944, b = 1.9385, Loss = 1.1958
Epoch 100: w = 3.3864, b = 1.9915, Loss = 1.1670

Kết quả cuối cùng:
w = 3.3864, b = 1.9915


In [ ]:
# pytorch with tensor
import torch
import numpy as np


In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
# Chuyển đổi mảng numpy sang Tensor pytorch
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [ ]:
print(x.dtype)

torch.int64


In [ ]:
print(x.type())

torch.LongTensor


In [ ]:
import numpy as np
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr2)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [ ]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [ ]:
#BTVN 3: Giải thích tại sao cho 2 trường hợp trên

In [ ]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [ ]:
arr[0] = 99
print (x)

tensor([0, 1, 2, 3, 4])


In [3]:
# BTCN 4
# Tạo tensor với:
# Empty
# Zeros
# Ones
# Randoms
# Reshape với view và view as
# Deadline 16/03
import torch

# 1. Tạo tensor với empty (không khởi tạo giá trị, chứa các giá trị rác)
tensor_empty = torch.empty(2, 3)  # Tạo tensor 2x3 không khởi tạo giá trị
print("Tensor empty:")
print(tensor_empty)

# 2. Tạo tensor với zeros (khởi tạo giá trị 0)
tensor_zeros = torch.zeros(2, 3)  # Tạo tensor 2x3 với tất cả giá trị là 0
print("\nTensor zeros:")
print(tensor_zeros)

# 3. Tạo tensor với ones (khởi tạo giá trị 1)
tensor_ones = torch.ones(2, 3)  # Tạo tensor 2x3 với tất cả giá trị là 1
print("\nTensor ones:")
print(tensor_ones)

# 4. Tạo tensor với random (khởi tạo giá trị ngẫu nhiên)
tensor_random = torch.rand(2, 3)  # Tạo tensor 2x3 với giá trị ngẫu nhiên từ phân phối đều [0, 1)
print("\nTensor random:")
print(tensor_random)

# 5. Reshape tensor với view
# Tạo một tensor có kích thước 2x3
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\nTensor ban đầu:")
print(tensor)

# Reshape tensor thành kích thước 3x2 bằng view
tensor_reshaped = tensor.view(3, 2)
print("\nTensor sau khi reshape với view (3x2):")
print(tensor_reshaped)

# 6. Reshape tensor với view_as
# Tạo một tensor khác có kích thước 3x2
tensor_target = torch.zeros(3, 2)

# Reshape tensor ban đầu thành cùng kích thước với tensor_target bằng view_as
tensor_reshaped_as = tensor.view_as(tensor_target)
print("\nTensor sau khi reshape với view_as (3x2):")
print(tensor_reshaped_as)

Tensor empty:
tensor([[2.3481e-34, 0.0000e+00, 2.6987e-34],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

Tensor zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor random:
tensor([[0.3087, 0.1211, 0.5354],
        [0.2840, 0.2553, 0.2822]])

Tensor ban đầu:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor sau khi reshape với view (3x2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Tensor sau khi reshape với view_as (3x2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])
